'use client';
import { useMemo, useState } from 'react';
import { Building2, Home, Search, UserRound, Package, UserCircle, Upload, Plus, Star, Clock3, FileText } from 'lucide-react';

type View = 'Home'|'Hospitals'|'Surgeons'|'Products'|'Account';

const seed = {
  hospitals:[
    {name:'Mission Bernal', detail:'Parking, Symplr/VCS sign-in, sterile core, inventory, trays', tags:['MBC','Sutter','VHN']},
    {name:'Novato Community Hospital', detail:'Vendor sign-in, VELYS storage, hip/knee consignment, trays', tags:['NCH','VELYS','Sutter']},
    {name:'Kaiser South SF', detail:'OR access, SPD code, Nagy/Haw hip trays and implants', tags:['KSSF','Hip']}
  ],
  surgeons:[
    {name:'Dr. Mayle', detail:'THA, non-robotic TKA, VELYS/VRAS TKA', tags:['THA','TKA','VELYS']},
    {name:'Dr. Haw', detail:'Anterior THA, Actis/Pinnacle, routine screw workflow', tags:['Anterior THA','Actis']},
    {name:'Dr. Detch', detail:'Anterior THA, x-ray overlays, Actis/Emphysis/Pinnacle', tags:['Anterior THA','Mills']}
  ],
  products:[
    {name:'ATTUNE', detail:'Primary TKA, revision, CR/PS/MS, surgical technique docs', tags:['Knee','Revision']},
    {name:'ACTIS', detail:'Anterior THA stem notes, broach/implant workflow', tags:['Hip','Stem']},
    {name:'VELYS / VRAS', detail:'Robot setup, registration, OR workflow, VHN cup check', tags:['Robot','Navigation']}
  ]
};

function NavButton({view,current,setView,icon}:{view:View,current:View,setView:(v:View)=>void,icon:any}){const Icon=icon;return <button className={current===view?'active':''} onClick={()=>setView(view)}><Icon size={18}/>{view}</button>}
function Item({title,detail,tags}:{title:string,detail:string,tags:string[]}){return <div className="item"><div><div className="item-title">{title}</div><div className="muted">{detail}</div><div style={{marginTop:8}}>{tags.map(t=><span key={t} className="pill">{t}</span>)}</div></div><span className="pill green">Open</span></div>}
function HomeView(){return <div className="grid"><section className="card span7"><h2>Favorites</h2><div className="list"><Item title="Dr. Mayle" detail="THA / TKA / VELYS workflows" tags={['Surgeon','Favorite']}/><Item title="Mission Bernal" detail="Hospital notes, trays, inventory, documents" tags={['Hospital','Favorite']}/></div></section><section className="card span5"><h2>Quick Actions</h2><div className="list"><button className="btn"><Plus size={16}/> Add Note</button><button className="btn secondary"><Upload size={16}/> Upload Document</button></div></section><section className="card span8"><h2>Recent Updates</h2><div className="list"><Item title="Mission Bernal trays updated" detail="Hip and knee consignment section edited" tags={['Inventory']}/><Item title="Dr. Haw pinned pearl added" detail="25mm screw backup reminder" tags={['Pinned Pearl']}/><Item title="ATTUNE guide uploaded" detail="Document tagged to product and knee procedure" tags={['Document']}/></div></section><section className="card span4"><h2>Recently Viewed</h2><div className="list"><Item title="Dr. Detch" detail="Anterior THA" tags={['Surgeon']}/><Item title="ACTIS" detail="Product notes" tags={['Product']}/></div></section></div>}
function ListView({title,items}:{title:string,items:{name:string,detail:string,tags:string[]}[]}){return <section className="card"><h2>{title}</h2><div className="tabs"><button className="active">All</button><button>Favorites</button><button>Recent</button></div><div className="list">{items.map(i=><Item key={i.name} title={i.name} detail={i.detail} tags={i.tags}/>)}</div></section>}
function AccountView(){return <section className="card"><h2>Account</h2><div className="section"><h3>Wilson H.</h3><p className="muted">Role: Admin · Profile style: initials only</p></div><div className="section"><h3>Admin Controls</h3><p className="muted">Invite users, manage roles, customize fields, templates, pinned pearls, and document tags.</p></div><div className="section"><h3>Offline Downloads</h3><p className="muted">Download surgeon pages, hospital pages, photos, and documents for poor-reception hospitals.</p></div></section>}
export default function Page(){const [view,setView]=useState<View>('Home');const [q,setQ]=useState('');const results=useMemo(()=>{const all=[...seed.hospitals,...seed.surgeons,...seed.products];return q?all.filter(x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase())):[]},[q]);return <div className="app"><aside className="sidebar"><div className="brand"><div className="logo"><Building2 size={24}/></div><div><h1>JointVault</h1><p>Team knowledge base</p></div></div><nav className="nav"><NavButton view="Home" current={view} setView={setView} icon={Home}/><NavButton view="Hospitals" current={view} setView={setView} icon={Building2}/><NavButton view="Surgeons" current={view} setView={setView} icon={UserRound}/><NavButton view="Products" current={view} setView={setView} icon={Package}/><NavButton view="Account" current={view} setView={setView} icon={UserCircle}/></nav></aside><main className="main"><div className="mobile-actions"><button className="btn"><Plus size={16}/> Add</button><button className="btn secondary"><Upload size={16}/> Upload</button></div><div className="topbar"><input className="search" placeholder="Search everything: surgeon, hospital, trays, implants, docs..." value={q} onChange={e=>setQ(e.target.value)}/><button className="btn"><Search size={16}/> Search</button></div>{q?<section className="card"><h2>Search Results</h2><div className="list">{results.map(i=><Item key={i.name} title={i.name} detail={i.detail} tags={i.tags}/>)}</div></section>:view==='Home'?<HomeView/>:view==='Hospitals'?<ListView title="Hospitals" items={seed.hospitals}/>:view==='Surgeons'?<ListView title="Surgeons" items={seed.surgeons}/>:view==='Products'?<ListView title="Products" items={seed.products}/>:<AccountView/>}</main><nav className="bottomnav"><button className={view==='Home'?'active':''} onClick={()=>setView('Home')}><Home size={18}/><br/>Home</button><button className={view==='Hospitals'?'active':''} onClick={()=>setView('Hospitals')}><Building2 size={18}/><br/>Hospitals</button><button className={view==='Surgeons'?'active':''} onClick={()=>setView('Surgeons')}><UserRound size={18}/><br/>Surgeons</button><button className={view==='Products'?'active':''} onClick={()=>setView('Products')}><Package size={18}/><br/>Products</button><button className={view==='Account'?'active':''} onClick={()=>setView('Account')}><UserCircle size={18}/><br/>Account</button></nav></div>}
